courses = {
    "Art History": "This course provides an overview of art and architecture from the paleolithic era through the fourteenth century, to include Prehistoric, Mesopotamian, Egyptian, Aegean, Greek, Etruscan, Roman, Early Christian, Byzantine, Islamic, Early Medieval, Romanesque, and Gothic periods. ",
    "Architecture": "This course provides students with an overview of professional occupations in Architecture, Construction Management, Building Inspection Technology, City and Regional Planning, Architectural Engineering and Landscape Architecture.",
    "Anthropology": "This course introduces the concepts, methods of inquiry, and scientific explanations for biological evolution and their application to the human species. It examines the origins of humans and their place in nature.",
    "Biology": "An introduction to biology for non-science majors including the study of plants, animals, ecology, and evolution. The foundations of biology, including biochemistry, cell biology, genetics, anatomy and physiology, and the impact of humans on the environment will be covered in this course.",
    "Dance": "This course is an introduction to the fundamental elements of choreography and their practical application in creating dance composition.",
    "Economics": "Macroeconomics deals with the overall performance of the economy. It focuses on aggregate economic concepts such as the gross domestic product, employment, unemployment, price stability, inflation, ups and downs of the economy, economic growth, the role of money, and the impact of international trade. The course also covers different theories and views that explain an economic system, and addresses a range of policy options that can be considered for improving the performance of the economy.",
    "Chemistry": "This is the first course of a two-semester sequence covering the basic principles and concepts of chemistry with emphasis on chemical calculations. Inorganic chemistry is stressed, and the material includes a discussion of atomic structure, chemical bonding, molecules, reaction types, states of matter, and the properties of solutions. The laboratory part of the course complements the lectures and includes qualitative analysis.",
    "English": "This course focuses on the elements of academic writing, including genre, audience and purpose, and argumentation. Students learn critical thinking, textual analysis, and research techniques, as they apply to the writing process, and they will compose essays using proper documentation, following MLA and/or APA rules.",
    "History": "This course is a broad study of the major elements of history from ancient times to the Renaissance. It is designed to develop understanding of institutions basic to world civilization.",
    "Engineering Technology": "This course is an introduction to robotics. The history of robots along with the components that constitute a robot will be covered. Students will learn to manipulate the basic building blocks of a robot by programming a microcontroller and interfacing with basic circuits, sensors and motors.",
}